import Link from "next/link";
import { UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function AdminPage() { await requireAdmin(); const [users, active, disabled, recent] = await Promise.all([prisma.profile.count(), prisma.profile.count({ where: { disabledAt: null } }), prisma.profile.count({ where: { disabledAt: { not: null } } }), prisma.auditEvent.findMany({ take: 5, orderBy: { createdAt: "desc" }, include: { actor: { select: { email: true } } } })]); return <AppShell isAdmin><PageHeader eyebrow="Administration" title="Platform overview" description="Support, account controls, and system health." /><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Total users</CardDescription><CardTitle className="text-3xl">{users}</CardTitle></CardHeader><CardContent><UsersRound className="size-5 text-[var(--primary)]" /></CardContent></Card><Card><CardHeader><CardDescription>Active accounts</CardDescription><CardTitle className="text-3xl">{active}</CardTitle></CardHeader><CardContent><p className="text-sm text-[var(--success)]">{users ? Math.round(active / users * 100) : 0}% enabled</p></CardContent></Card><Card><CardHeader><CardDescription>Disabled accounts</CardDescription><CardTitle className="text-3xl">{disabled}</CardTitle></CardHeader><CardContent><p className="text-sm text-[var(--muted-foreground)]">Access currently blocked</p></CardContent></Card></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Admin tools</CardTitle></CardHeader><CardContent className="grid gap-3"><Link className="rounded-lg border p-4 hover:bg-[var(--muted)]" href="/admin/users"><b>User support</b><p className="mt-1 text-sm text-[var(--muted-foreground)]">Search, inspect, disable, or reset accounts.</p></Link><Link className="rounded-lg border p-4 hover:bg-[var(--muted)]" href="/admin/audit"><b>Audit log</b><p className="mt-1 text-sm text-[var(--muted-foreground)]">Review administrative activity.</p></Link><Link className="rounded-lg border p-4 hover:bg-[var(--muted)]" href="/admin/health"><b>System health</b><p className="mt-1 text-sm text-[var(--muted-foreground)]">Check application and database status.</p></Link></CardContent></Card><Card><CardHeader><CardTitle>Recent admin actions</CardTitle></CardHeader><CardContent className="space-y-3">{recent.length ? recent.map((event) => <div key={event.id} className="border-b pb-3 last:border-0"><p className="text-sm font-medium">{event.action}</p><p className="text-xs text-[var(--muted-foreground)]">{event.actor?.email ?? "System"} · {event.createdAt.toLocaleString()}</p></div>) : <p className="text-sm text-[var(--muted-foreground)]">No administrative actions yet.</p>}</CardContent></Card></div></AppShell>; }
