import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireUser } from "@/lib/auth";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { addJobDeduction, archiveJob, createJob, deleteJobDeduction, updateJobPay } from "@/app/actions/work";
import { formatCents } from "@/lib/earnings";
import { formatMinutes } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function JobsPage() {
  const profile = await requireUser();
  const supabase = await createServerSupabaseClient();
  const { data: jobs } = await supabase.from("jobs").select("id,name,color,weekly_limit_minutes,hourly_rate_cents,tax_rate_basis_points,job_deductions(id,name,rate_basis_points)").eq("user_id", profile.id).is("archived_at", null).order("name");
  return <AppShell isAdmin={profile.role === "ADMIN"}><PageHeader eyebrow="Jobs" title="Jobs, pay, and deductions" description="Rates are saved onto each new shift, so changing them never changes past earnings." />
    <div className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
      <Card><CardHeader><CardTitle>Your active jobs</CardTitle></CardHeader><CardContent className="space-y-3">{jobs?.length ? jobs.map((job) => <div key={job.id} className="rounded-lg border p-4"><div className="flex items-center gap-3"><span className="size-3 rounded-full" style={{ background: job.color }} /><div className="flex-1"><p className="font-medium">{job.name}</p><p className="text-sm text-[var(--muted-foreground)]">{formatCents(job.hourly_rate_cents)}/hr · {job.tax_rate_basis_points / 100}% tax · {job.weekly_limit_minutes ? `${formatMinutes(job.weekly_limit_minutes)} weekly limit` : "No hour limit"}</p></div><form action={archiveJob}><input type="hidden" name="id" value={job.id} /><Button variant="ghost" size="sm">Archive</Button></form></div><details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-medium text-[var(--primary)]">Manage pay and deductions</summary><div className="mt-4 grid gap-5"><form action={updateJobPay} className="grid gap-3 sm:grid-cols-3"><input type="hidden" name="id" value={job.id} /><label className="grid gap-1 text-xs font-medium">Hourly rate ($)<input name="hourlyRate" type="text" inputMode="decimal" defaultValue={(job.hourly_rate_cents / 100).toFixed(2)} className="h-9 rounded-md border bg-transparent px-2 text-sm" /></label><label className="grid gap-1 text-xs font-medium">Tax (%)<input name="taxRate" type="text" inputMode="decimal" defaultValue={(job.tax_rate_basis_points / 100).toFixed(2)} className="h-9 rounded-md border bg-transparent px-2 text-sm" /></label><div className="flex items-end"><Button size="sm" type="submit">Save pay</Button></div></form><div><p className="mb-2 text-xs font-medium text-[var(--muted-foreground)]">Percentage deductions</p><div className="space-y-2">{job.job_deductions.map((deduction) => <div key={deduction.id} className="flex items-center justify-between rounded-md bg-[var(--muted)] px-3 py-2 text-sm"><span>{deduction.name} · {deduction.rate_basis_points / 100}%</span><form action={deleteJobDeduction}><input type="hidden" name="id" value={deduction.id} /><Button size="sm" variant="ghost">Remove</Button></form></div>)}</div><form action={addJobDeduction} className="mt-3 grid gap-2 sm:grid-cols-[1fr_110px_auto]"><input type="hidden" name="jobId" value={job.id} /><input name="name" required maxLength={80} placeholder="e.g. Retirement" className="h-9 rounded-md border bg-transparent px-2 text-sm" /><input name="rate" required placeholder="3.00" inputMode="decimal" className="h-9 rounded-md border bg-transparent px-2 text-sm" /><Button size="sm" type="submit">Add</Button></form></div></div></details></div>) : <p className="py-8 text-center text-sm text-[var(--muted-foreground)]">No jobs created yet.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Add a job</CardTitle></CardHeader><CardContent><form action={createJob} className="grid gap-4"><label className="grid gap-1.5 text-sm font-medium">Job name<input name="name" required maxLength={80} className="h-10 rounded-lg border bg-transparent px-3" placeholder="e.g. Campus desk" /></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1.5 text-sm font-medium">Hourly rate ($)<input name="hourlyRate" required inputMode="decimal" placeholder="18.50" className="h-10 rounded-lg border bg-transparent px-3" /></label><label className="grid gap-1.5 text-sm font-medium">Tax rate (%)<input name="taxRate" required inputMode="decimal" defaultValue="0" className="h-10 rounded-lg border bg-transparent px-3" /></label></div><label className="grid gap-1.5 text-sm font-medium">Color<input name="color" type="color" defaultValue="#9486ff" className="h-10 w-full rounded-lg border bg-transparent p-1" /></label><label className="grid gap-1.5 text-sm font-medium">Weekly limit (minutes)<input name="weeklyLimitMinutes" type="number" min={1} max={10080} className="h-10 rounded-lg border bg-transparent px-3" placeholder="Leave blank for no limit" /></label><p className="text-xs text-[var(--muted-foreground)]">You can add named percentage deductions after creating the job.</p><Button type="submit">Create job</Button></form></CardContent></Card>
    </div>
  </AppShell>;
}
