import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { sendPasswordReset, setAccountDisabled } from "@/app/actions/admin";

export const dynamic = "force-dynamic";

export default async function AdminUserPage({ params }: { params: Promise<{ id: string }> }) { await requireAdmin(); const { id } = await params; const user = await prisma.profile.findUnique({ where: { id }, include: { jobs: { orderBy: { createdAt: "desc" } }, shifts: { take: 10, orderBy: { startsAt: "desc" }, include: { job: { select: { name: true } } } } } }); if (!user) return <AppShell isAdmin><p>User not found.</p></AppShell>; return <AppShell isAdmin><PageHeader eyebrow="User support" title={user.displayName ?? user.email} description={user.email} actions={<Link href="/admin/users"><Button variant="outline">Back to users</Button></Link>} /><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Account</CardTitle></CardHeader><CardContent className="space-y-3"><p className="flex justify-between text-sm"><span className="text-[var(--muted-foreground)]">Role</span><Badge>{user.role}</Badge></p><p className="flex justify-between text-sm"><span className="text-[var(--muted-foreground)]">Status</span><Badge variant={user.disabledAt ? "danger" : "success"}>{user.disabledAt ? "Disabled" : "Enabled"}</Badge></p><p className="text-sm text-[var(--muted-foreground)]">Joined {user.createdAt.toLocaleDateString()}</p><div className="flex flex-wrap gap-3 pt-3"><form action={setAccountDisabled}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="disabled" value={String(!user.disabledAt)} /><Button variant={user.disabledAt ? "default" : "danger"}>{user.disabledAt ? "Enable account" : "Disable account"}</Button></form><form action={sendPasswordReset}><input type="hidden" name="userId" value={user.id} /><Button variant="outline">Send password reset</Button></form></div></CardContent></Card><Card><CardHeader><CardTitle>Data summary</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>{user.jobs.length} jobs</p><p>{user.shifts.length} recent shifts</p><div className="mt-4 divide-y">{user.shifts.map((shift) => <div className="py-2" key={shift.id}><b>{shift.job.name}</b><p className="text-[var(--muted-foreground)]">{shift.startsAt.toLocaleString()} – {shift.endsAt.toLocaleTimeString()}</p></div>)}</div></CardContent></Card></div></AppShell>; }
