"use client";

import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, Clock3, Sparkles, WalletCards } from "lucide-react";
import Link from "next/link";
import { formatInTimeZone } from "date-fns-tz";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { formatHours, formatMinutes } from "@/lib/utils";
import { formatCents } from "@/lib/earnings";
import type { DashboardData } from "@/lib/types";

function capPercent(used: number, limit: number | null) { return limit ? Math.round((used / limit) * 100) : 0; }

export function DashboardView({ data, isAdmin = false }: { data: DashboardData; isAdmin?: boolean }) {
  const projected = data.loggedMinutes + data.scheduledMinutes;
  const globalPercent = capPercent(projected, data.globalLimitMinutes);
  const remaining = data.globalLimitMinutes === null ? null : Math.max(0, data.globalLimitMinutes - projected);
  return <AppShell isAdmin={isAdmin} isDemo={data.isDemo}>
    <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
      <div><p className="mb-1 text-sm font-medium text-[var(--primary)]">{data.isDemo ? "Workspace preview" : "Weekly overview"}</p><h1 className="text-3xl font-bold tracking-tight">Good {new Date().getHours() < 12 ? "morning" : "afternoon"}, {data.viewer.name ?? "there"}.</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">Your week starts on {new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(new Date(2026, 7, 16 + data.viewer.weekStartsOn))} in {data.viewer.timeZone}.</p></div>
      {data.isDemo && <Badge variant="muted"><Sparkles className="mr-1 size-3" />Sample data</Badge>}
    </div>

    {data.alerts.map((alert) => <div key={`${alert.title}-${alert.level}`} className="mb-4 flex items-start gap-3 rounded-xl border border-[color-mix(in_srgb,var(--warning)_35%,var(--border))] bg-[color-mix(in_srgb,var(--warning)_9%,transparent)] p-4"><AlertTriangle className="mt-0.5 size-5 text-[var(--warning)]" /><div><p className="font-semibold">{alert.title}</p><p className="mt-0.5 text-sm text-[var(--muted-foreground)]">{alert.detail}</p></div></div>)}

    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Card className="xl:col-span-2"><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Global weekly cap</CardTitle><CardDescription>Logged plus scheduled hours</CardDescription></div><Badge variant={globalPercent >= 100 ? "danger" : globalPercent >= 80 ? "warning" : "success"}>{data.globalLimitMinutes ? `${globalPercent}% planned` : "No cap"}</Badge></div></CardHeader><CardContent><div className="mb-3 flex items-baseline gap-2"><span className="text-3xl font-bold">{formatHours(projected)}h</span><span className="text-sm text-[var(--muted-foreground)]">of {data.globalLimitMinutes ? `${formatHours(data.globalLimitMinutes)}h` : "unlimited"}</span></div><Progress value={globalPercent} indicatorClassName={globalPercent >= 100 ? "bg-[var(--danger)]" : globalPercent >= 80 ? "bg-[var(--warning)]" : "bg-[var(--success)]"} /><div className="mt-3 flex justify-between text-xs text-[var(--muted-foreground)]"><span>{formatMinutes(data.loggedMinutes)} logged</span><span>{formatMinutes(data.scheduledMinutes)} scheduled</span></div></CardContent></Card>
      <Card><CardHeader><CardDescription>Remaining availability</CardDescription><CardTitle className="text-3xl">{remaining === null ? "—" : formatHours(remaining) + "h"}</CardTitle></CardHeader><CardContent><p className="text-sm text-[var(--muted-foreground)]">{remaining === null ? "Set a cap in Settings to track availability." : "before your planned global limit."}</p></CardContent></Card>
      <Card><CardHeader><CardDescription>Upcoming shifts</CardDescription><CardTitle className="text-3xl">{data.upcomingShifts.length}</CardTitle></CardHeader><CardContent><p className="text-sm text-[var(--muted-foreground)]">scheduled this week</p></CardContent></Card>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2"><WalletCards className="size-5 text-[var(--success)]" />Earned this week</CardTitle><CardDescription>Completed work plus time elapsed on any active shift.</CardDescription></div><Badge variant="success">Net {formatCents(data.earnings.netCents)}</Badge></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-4"><div className="rounded-lg bg-[var(--muted)] p-3"><p className="text-xs text-[var(--muted-foreground)]">Gross</p><p className="mt-1 font-semibold">{formatCents(data.earnings.grossCents)}</p></div><div className="rounded-lg bg-[var(--muted)] p-3"><p className="text-xs text-[var(--muted-foreground)]">Tax</p><p className="mt-1 font-semibold">−{formatCents(data.earnings.taxCents)}</p></div><div className="rounded-lg bg-[var(--muted)] p-3"><p className="text-xs text-[var(--muted-foreground)]">Deductions</p><p className="mt-1 font-semibold">−{formatCents(data.earnings.deductionCents)}</p></div><div className="rounded-lg bg-[color-mix(in_srgb,var(--success)_12%,transparent)] p-3"><p className="text-xs text-[var(--muted-foreground)]">Net earned</p><p className="mt-1 font-semibold text-[var(--success)]">{formatCents(data.earnings.netCents)}</p></div></div><div className="mt-5 space-y-2">{data.jobs.map((job) => <div key={job.id} className="flex justify-between text-sm"><span className="flex items-center gap-2"><i className="size-2 rounded-full" style={{ background: job.color }} />{job.name}</span><span className="font-medium">{formatCents(job.earnedNetCents)}</span></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Net earnings history</CardTitle><CardDescription>Earned net pay by week.</CardDescription></CardHeader><CardContent className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.earningsHistory} margin={{ left: -15, right: 4, top: 4 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} tickFormatter={(value) => `$${Math.round(Number(value) / 100)}`} /><Tooltip cursor={{ fill: "var(--muted)" }} formatter={(value) => formatCents(Number(value))} /><Bar dataKey="netCents" fill="var(--success)" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Weekly history</CardTitle><CardDescription>Logged hours over the last five weeks</CardDescription></div></div></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.history} margin={{ left: -20, right: 8, top: 4 }}><CartesianGrid vertical={false} stroke="var(--border)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} tickFormatter={(value) => `${Math.round(value / 60)}h`} /><Tooltip cursor={{ fill: "var(--muted)" }} formatter={(value) => `${formatHours(Number(value))}h`} /><Bar dataKey="loggedMinutes" fill="var(--primary)" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card>
      <Card><CardHeader><CardTitle>Hours by job</CardTitle><CardDescription>Includes future shifts in this week.</CardDescription></CardHeader><CardContent className="space-y-5">{data.jobs.length ? data.jobs.map((job) => { const planned = job.usedMinutes + job.scheduledMinutes; const percent = capPercent(planned, job.weeklyLimitMinutes); return <div key={job.id}><div className="mb-2 flex justify-between gap-3 text-sm"><span className="flex items-center gap-2 font-medium"><i className="size-2.5 rounded-full" style={{ background: job.color }} />{job.name}</span><span className="text-[var(--muted-foreground)]">{formatHours(planned)}h{job.weeklyLimitMinutes ? ` / ${formatHours(job.weeklyLimitMinutes)}h` : ""}</span></div><Progress value={percent} indicatorClassName={percent >= 100 ? "bg-[var(--danger)]" : percent >= 80 ? "bg-[var(--warning)]" : ""} /></div>; }) : <p className="py-8 text-center text-sm text-[var(--muted-foreground)]">Add a job to start tracking its limit.</p>}</CardContent></Card>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Coming up</CardTitle><CardDescription>Your next scheduled shifts</CardDescription></div><Link href="/shifts" className="text-sm font-medium text-[var(--primary)]">See all</Link></div></CardHeader><CardContent className="divide-y">{data.upcomingShifts.length ? data.upcomingShifts.map((shift) => <div key={shift.id} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className="grid size-9 place-items-center rounded-lg" style={{ background: `${shift.jobColor}22`, color: shift.jobColor }}><Clock3 className="size-4" /></span><div className="min-w-0 flex-1"><p className="font-medium">{shift.jobName}</p><p className="truncate text-sm text-[var(--muted-foreground)]">{formatInTimeZone(shift.startsAt, data.viewer.timeZone, "EEE, MMM d · h:mm a")} – {formatInTimeZone(shift.endsAt, data.viewer.timeZone, "h:mm a")}</p></div><ArrowRight className="size-4 text-[var(--muted-foreground)]" /></div>) : <p className="py-8 text-center text-sm text-[var(--muted-foreground)]">Nothing scheduled this week.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>How projections work</CardTitle><CardDescription>Stay ahead instead of reacting late.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex gap-3"><CheckCircle2 className="size-5 shrink-0 text-[var(--success)]" />Past and current shifts count as logged time.</p><p className="flex gap-3"><CalendarClock className="size-5 shrink-0 text-[var(--primary)]" />Future shifts are included in your projected total.</p><p className="flex gap-3"><AlertTriangle className="size-5 shrink-0 text-[var(--warning)]" />We alert you at 80%, 90%, and 100%.</p></CardContent></Card>
    </section>
  </AppShell>;
}
